name: climate-gpt
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pytorch
  - sentencepiece
  - jupyterlab
  - ipykernel
  - structlog
  - tqdm
  - black[jupyter]
  - flake8
  - pre-commit
  - pytest
  - pip
  - pip:
    - -e .
